### PR TITLE
Boosting this timeout so we don't have more issues. Should probably f…

### PR DESCRIPTION
**Pull request by colin-hanson-zocdoc**
…urther optimize this query

@Lal-kottu-zocdoc @chris-smith-zocdoc 

This query timed out on three consecutive main ci runs this morning.  While boosting the timeout is definitely not the best solution it should help prevent this from happening again in the future.

### CODE REVIEW

**Comment by Lal-kottu-zocdoc** [comment]
:+1: definitely less hacky than the other solution

**Comment by Lal-kottu-zocdoc** [comment]
Just ran this on metrics_datawarehouse in production/repl-db.

It runs as part of the metrics deploy - took 70 seconds :hankey: 

i'll look into getting this to behave but if you boys have ideas lmk

**Comment by colin-hanson-zocdoc** [comment]
Hm do you think I should bother merging this then? I could set the timeout even higher but that's obviously not ideal... I can't believe it takes so long

**Comment by Lal-kottu-zocdoc** [comment]
you should merge this. if it gets higher than this, its a sign for us to fix it ASAP! 

but we should not be bogged down by failed runs at 30 seconds.

**Pull request merged**
