### PR TITLE
Expose BuildActionType

### PR DESCRIPTION
**Pull request by chris-smith-zocdoc**
@colin-hanson-zocdoc @marcio-santos-zocdoc @scott-roepnack-zocdoc 

Expose BuildActionType so other projects can introspect what executing a build will do.

### CODE REVIEW

**Comment by scott-roepnack-zocdoc** [comment]
This looks good to me, but can you provide a bit more content.  What's a use case someone would want to know this, and at what level of the stack?

**Comment by kyle-fritz-zocdoc** [comment]
:+1:

**Comment by jameszhao00** [comment]
:+1:

**Comment by matthew-piziak** [comment]
:+1:

**Comment by chris-smith-zocdoc** [comment]
@scott-roepnack-zocdoc The use case is while using this library, you figure out which objects need to be redeployed
```cs
ICollection<BuildItem> buildItems = await db.GetChangedBuildItemsAsync(repo)
```

But you don't know what action will be taken when you call

```cs
await db.BuildAsync(buildItems);
```

By exposing `BuildActionType` we can inspect the `BuildItem` to see what action will be taken.

**Pull request merged**
